### PR TITLE
Add credit to RPDB in Readme

### PR DESCRIPTION
**Pull request by jaruba**
As per the [discussion on reddit](https://www.reddit.com/r/jellyfin/comments/m8rxsa/cover_ratings/gsyuhyp?utm_source=share&utm_medium=web2x&context=3), this PR adds a credit note in the readme file for the original project that inspired it.

### CODE REVIEW

**Comment by ilarramendi** [comment]
As i told you i will, its already added, no need to worry!

**Comment by jaruba** [comment]
I'm afraid that adding it at the bottom of your readme is unacceptable. This is not a note regarding collaborators to your project, this is a note regarding where the entire concept of your project, technique of injecting posters and design that you have advertised it with in numerous places came from.

This means that you need to make it abundantly clear where it came from, at the top of your readme. As much as I appreciate that you thought this concept was cool and you should work on it, it is a product of a firm and it is not your's, it is mine, so you should make that clear and visible to your users.

**Comment by ilarramendi** [comment]
Im afraid that this is what i can offer, since this project in no way shares code with what you have created and the technique to add the posters wasnt copied from your project, just a simple google search and found the very usefull emby and plex documentation.  
Also how is the message not clear enought? since its the same that you wrote.

If its how it looks whats bothering you i can change the default look and the idea of the project is to be fully customizable by users (Also its a very simple layout, thers not much more to change, its just a couple of icons and a value).  
Aditionaly this has a very similar look with the side-bar to the plugin [CoverArt](https://emby.media/community/index.php?/topic/800-coverart-40/) for emby, from 2013... Which since whe are speaking about that probably uses the same "technique" that you said to inject images to posters.  
Hope you understand my point of view, have a great day!

**Comment by jaruba** [comment]
CoverArt is a plugin, it does not use the same technique, it is specific to Emby only. Your point of view is flawed.

Did you check the docs of those apps before seeing my project? Did you think of building this before seeing my project, what it does and how it does it? The answer to all of these is no.

If you are creating a cross-media center ratings on posters solution, and you started it right after seeing my project, than you should easily realize that what you are doing literally came from me and my effort and lacks original thought.

Are you sure that you do not wish to cooperate in regards to my very simple request?

**Comment by ilarramendi** [comment]
Yes of course this project what inspired by RPDB! thats why i added this to the readme:

> This project was inspired by [Rating Poster Database](https://ratingposterdb.com/)!

Aditionaly coverart uses the same technique to inject metadata on posters so thats nothing new, it just saves the cover on another place and yes i knew about that plugin a long time ago, its just very old and bad, and it being cross platform isnt meant by desingn, this was meant to work for my use case on emby, it just happends to work with the other most common streaming platforms and thats a feature that should be known!

I think that i have cooperated with you adding exactly what you asked to the readme, just dont think adding it to the top is neccesary!

**Comment by jaruba** [comment]
> just dont think adding it to the top is neccesary!

Ofc it's not necessary, and in a different scenario I wouldn't ask for it, but i am currently still in a beta myself, and in an effort of advertising RPDB also.

Given that you have chosen to advertise it in the exact same way that I did, and you targeted the exact same user base as I did with the exact same purpose (cross media-center ratings on posters). This means that you did hurt, and are actively hurting RPDB's chances of breaching the market itself, and it's chances at profits from the exact same users.

This is causing a big problem for me, I will never get a chance of reaching these users that you reached out to first. Although putting that note at the top of the readme is not necessary, it's a sign of good faith that will reduce the impact of your own advertising (in a minor way) at breaking RPDB's chances, it means that you are not hurting the project that sparked your own project intentionally.

At the end of the day I don't see how your users would choose RPDB over your project as your's is free, and as you stated is progressing towards being more diverse (although still named Cover Ratings...) but they will at least know RPDB exists, which a foot note might not accomplish in the same way.

Whether you choose to put it on top of the readme or not, I won't debate this further, but you once said that you did not wish to hurt my project, please realise that you are doing this right now.. What I am asking for will simply reduce future damage that can be done.

I'll attach some screenshots so you can get a better understanding of what I mean by this.

My advertising post:

mine

Your advertising posts:

Screen Shot 2021-04-02 at 21 05 27

Screen Shot 2021-04-02 at 21 06 36

Screen Shot 2021-04-02 at 21 05 59

I think these screenshots clearly show the issue that I'm trying to highlight in this comment..

**Pull request closed without merging**
